[build]
builder = "DOCKERFILE"
dockerfilePath = "./api/Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 2 --log-level warning"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
